<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        h1 { color: #2c3e50; font-size: 24px; text-align: center; }
        h3 { color: #34495e; font-size: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #e74c3c; color: white; padding: 10px; border: 1px solid #c0392b; }
        td { padding: 8px; border: 1px solid #bdc3c7; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary { margin: 20px 0; padding: 15px; background-color: #f8f9fa; }
        .amount { text-align: right; }
        .footer { margin-top: 30px; font-size: 10px; color: #7f8c8d; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
        <p>Period: {{ request('start_date') }} to {{ request('end_date') }}</p>
    </div>

    @if(!empty($pdfData))
        @php
            $totalQuantity = collect($pdfData)->sum('Quantity Sold');
            $flavors = collect($pdfData)->groupBy('Flavor')->map(function($group) {
                return $group->sum('Quantity Sold');
            });
        @endphp

        <div class="summary">
            <h3>Summary</h3>
            <p><strong>Total Flavors:</strong> {{ $flavors->count() }}</p>
            <p><strong>Total Quantity Sold:</strong> {{ $totalQuantity }}</p>
            <p><strong>Top Flavor:</strong> {{ $flavors->sortDesc()->keys()->first() }} ({{ $flavors->sortDesc()->first() }} units)</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Flavor</th>
                    <th>Year</th>
                    <th>Month</th>
                    <th>Quantity</th>
                    <th>Orders</th>
                    <th>Avg per Order</th>
                </tr>
            </thead>
            <tbody>
                @foreach($pdfData as $row)
                <tr>
                    <td><strong>{{ $row['Flavor'] }}</strong></td>
                    <td>{{ $row['Year'] }}</td>
                    <td>{{ $row['Month'] }}</td>
                    <td style="text-align: center;">{{ $row['Quantity Sold'] }}</td>
                    <td style="text-align: center;">{{ $row['Order Count'] }}</td>
                    <td class="amount">{{ $row['Avg per Order'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="text-align: center; color: #e74c3c;">No data available for the selected period.</p>
    @endif

    <div class="footer">
        <p>Generated by Cake Shop Management System</p>
    </div>
</body>
</html>
