<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; }
        h1 { color: #2c3e50; font-size: 24px; text-align: center; }
        h3 { color: #34495e; font-size: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #2c3e50; color: white; padding: 8px; border: 1px solid #34495e; }
        td { padding: 6px; border: 1px solid #bdc3c7; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .amount { text-align: right; }
        .footer { margin-top: 30px; font-size: 10px; color: #7f8c8d; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
        <p>Period: {{ request('start_date') }} to {{ request('end_date') }}</p>
    </div>

    @if(!empty($pdfData))
        <table>
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Date</th>
                    <th>Customer</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Type</th>
                    <th>Custom</th>
                    <th>Occasion</th>
                </tr>
            </thead>
            <tbody>
                @foreach($pdfData as $row)
                <tr>
                    <td>#{{ $row['Order ID'] }}</td>
                    <td>{{ $row['Date'] }}</td>
                    <td>{{ $row['Customer'] }}</td>
                    <td class="amount">${{ number_format($row['Total'], 2) }}</td>
                    <td>{{ $row['Status'] }}</td>
                    <td>{{ $row['Order Type'] }}</td>
                    <td>{{ $row['Is Custom'] }}</td>
                    <td>{{ $row['Occasion'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="text-align: center; color: #e74c3c;">No data available for the selected period.</p>
    @endif

    <div class="footer">
        <p>Generated by Cake Shop Management System</p>
    </div>
</body>
</html>
