<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        h1 { color: #2c3e50; font-size: 24px; text-align: center; }
        h3 { color: #34495e; font-size: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f39c12; color: white; padding: 10px; border: 1px solid #e67e22; }
        td { padding: 8px; border: 1px solid #bdc3c7; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary { margin: 20px 0; padding: 15px; background-color: #f8f9fa; }
        .amount { text-align: right; }
        .stock-low { color: #e74c3c; font-weight: bold; }
        .stock-medium { color: #f39c12; font-weight: bold; }
        .stock-high { color: #27ae60; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; color: #7f8c8d; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
        <p>Period: {{ request('start_date') }} to {{ request('end_date') }}</p>
    </div>

    @if(!empty($pdfData))
        @php
            $totalRevenue = collect($pdfData)->sum('Total Revenue');
            $totalQuantity = collect($pdfData)->sum('Quantity Sold');
            $totalProducts = count($pdfData);
        @endphp

        <div class="summary">
            <h3>Summary</h3>
            <p><strong>Total Products:</strong> {{ $totalProducts }}</p>
            <p><strong>Total Quantity Sold:</strong> {{ $totalQuantity }}</p>
            <p><strong>Total Revenue:</strong> ${{ number_format($totalRevenue, 2) }}</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>SKU</th>
                    <th>Stock</th>
                    <th>Quantity Sold</th>
                    <th>Orders</th>
                    <th>Revenue</th>
                    <th>Avg Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach($pdfData as $row)
                <tr>
                    <td>{{ $row['Product Name'] }}</td>
                    <td>{{ $row['SKU'] }}</td>
                    <td style="text-align: center;">
                        @if($row['Current Stock'] <= 5)
                            <span class="stock-low">{{ $row['Current Stock'] }}</span>
                        @elseif($row['Current Stock'] <= 10)
                            <span class="stock-medium">{{ $row['Current Stock'] }}</span>
                        @else
                            <span class="stock-high">{{ $row['Current Stock'] }}</span>
                        @endif
                    </td>
                    <td style="text-align: center;">{{ $row['Quantity Sold'] }}</td>
                    <td style="text-align: center;">{{ $row['Order Count'] }}</td>
                    <td class="amount">${{ number_format($row['Total Revenue'], 2) }}</td>
                    <td class="amount">${{ number_format($row['Average Price'], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="text-align: center; color: #e74c3c;">No data available for the selected period.</p>
    @endif

    <div class="footer">
        <p>Generated by Cake Shop Management System</p>
    </div>
</body>
</html>
