<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; }
        h1 { color: #333; font-size: 18px; text-align: center; }
        h3 { color: #666; font-size: 14px; margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #4CAF50; color: white; font-weight: bold; text-align: left; padding: 8px; border: 1px solid #ddd; }
        td { padding: 8px; border: 1px solid #ddd; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary { margin: 20px 0; padding: 10px; background-color: #f9f9f9; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; text-align: center; }
        .amount { text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sales Report</h1>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
        <p>Period: {{ request('start_date') }} to {{ request('end_date') }}</p>
        <p>Report Type: {{ ucfirst(request('report', 'daily')) }}</p>
    </div>

    @if($data->count() > 0)
    <div class="summary">
        <h3>Summary</h3>
        <p>Total Records: {{ $data->count() }}</p>
        @if(request('report') == 'daily')
            <p>Total Revenue: ${{ number_format($data->sum('Total Revenue'), 2) }}</p>
            <p>Total Orders: {{ $data->sum('Total Orders') }}</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                @foreach(array_keys($data->first()->toArray()) as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
                <tr>
                    @foreach($row->toArray() as $key => $value)
                        <td class="{{ strpos($key, 'Revenue') !== false || strpos($key, 'Price') !== false || strpos($key, 'Value') !== false ? 'amount' : '' }}">
                            @if(is_numeric($value) && (strpos($key, 'Revenue') !== false || strpos($key, 'Price') !== false || strpos($key, 'Value') !== false))
                                ${{ number_format($value, 2) }}
                            @elseif(is_numeric($value) && strpos($key, 'Quantity') !== false)
                                {{ number_format($value) }}
                            @else
                                {{ $value }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p>No data available for the selected period.</p>
    @endif

    <div class="footer">
        <p>Generated by Cake Shop Management System</p>
    </div>
</body>
</html>
