<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        h1 { color: #2c3e50; font-size: 24px; text-align: center; }
        h3 { color: #34495e; font-size: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #9b59b6; color: white; padding: 10px; border: 1px solid #8e44ad; }
        td { padding: 8px; border: 1px solid #bdc3c7; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary { margin: 20px 0; padding: 15px; background-color: #f8f9fa; }
        .amount { text-align: right; }
        .rank-1 { background-color: #f1c40f; font-weight: bold; }
        .rank-2 { background-color: #bdc3c7; font-weight: bold; }
        .rank-3 { background-color: #e67e22; font-weight: bold; color: white; }
        .footer { margin-top: 30px; font-size: 10px; color: #7f8c8d; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
        <p>Period: {{ request('start_date') }} to {{ request('end_date') }}</p>
    </div>

    @if(!empty($pdfData))
        @php
            $totalRevenue = collect($pdfData)->sum('Total Revenue');
            $totalQuantity = collect($pdfData)->sum('Quantity Sold');
        @endphp

        <div class="summary">
            <h3>Summary</h3>
            <p><strong>Top {{ count($pdfData) }} Cakes</strong></p>
            <p><strong>Total Quantity Sold:</strong> {{ $totalQuantity }}</p>
            <p><strong>Total Revenue:</strong> ${{ number_format($totalRevenue, 2) }}</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Cake Name</th>
                    <th>Flavor</th>
                    <th>Quantity</th>
                    <th>Orders</th>
                    <th>Revenue</th>
                    <th>Avg Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach($pdfData as $row)
                <tr>
                    <td style="text-align: center;">#{{ $row['Rank'] }}</td>
                    <td>{{ $row['Product Name'] }}</td>
                    <td>{{ $row['Flavor'] }}</td>
                    <td style="text-align: center;">{{ $row['Quantity Sold'] }}</td>
                    <td style="text-align: center;">{{ $row['Times Ordered'] }}</td>
                    <td class="amount">${{ number_format($row['Total Revenue'], 2) }}</td>
                    <td class="amount">${{ number_format($row['Average Price'], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="text-align: center; color: #e74c3c;">No data available for the selected period.</p>
    @endif

    <div class="footer">
        <p>Generated by Cake Shop Management System</p>
    </div>
</body>
</html>
